import { I18nManager } from 'react-native';
import { createContext, PropsWithChildren, useContext, useEffect, useMemo, useState } from 'react';

import { readStoredJson, storageKeys, writeStoredJson } from '@/src/storage/persistence';

export type AppLanguage = 'ar' | 'en' | 'fr';

type TranslationKey =
  | 'common.language'
  | 'common.notifications'
  | 'common.signOut'
  | 'help.phoneRecoveryScaffold'
  | 'payments.simulatedNotice'
  | 'receipts.simulatedProof'
  | 'support.contactAgency';

const translations: Record<AppLanguage, Record<TranslationKey, string>> = {
  fr: {
    'common.language': 'Langue',
    'common.notifications': 'Notifications',
    'common.signOut': 'Se déconnecter',
    'help.phoneRecoveryScaffold':
      'La récupération par téléphone nécessite Firebase Phone Auth. Elle est préparée, mais pas activée dans cette version.',
    'payments.simulatedNotice':
      'Paiement simulé: aucun débit bancaire réel ni split financier réel n’est exécuté.',
    'receipts.simulatedProof':
      'Quittance générée par AtouPay selon les informations enregistrées. Elle ne vaut pas certification bancaire ou gouvernementale automatique.',
    'support.contactAgency': 'Contactez votre agence pour assistance.',
  },
  en: {
    'common.language': 'Language',
    'common.notifications': 'Notifications',
    'common.signOut': 'Sign out',
    'help.phoneRecoveryScaffold':
      'Phone recovery requires Firebase Phone Auth. It is prepared, but not enabled in this version.',
    'payments.simulatedNotice':
      'Simulated payment: no real bank debit or financial split is executed.',
    'receipts.simulatedProof':
      'Receipt generated by AtouPay from recorded system information. It is not automatically bank- or government-certified.',
    'support.contactAgency': 'Contact your agency for assistance.',
  },
  ar: {
    'common.language': 'اللغة',
    'common.notifications': 'الإشعارات',
    'common.signOut': 'تسجيل الخروج',
    'help.phoneRecoveryScaffold':
      'استرداد الحساب عبر الهاتف يتطلب تفعيل Firebase Phone Auth. الإعداد موجود لكنه غير مفعل في هذا الإصدار.',
    'payments.simulatedNotice':
      'دفع تجريبي: لا يتم تنفيذ أي خصم بنكي حقيقي أو توزيع مالي حقيقي.',
    'receipts.simulatedProof':
      'إيصال تم إنشاؤه بواسطة AtouPay حسب المعلومات المسجلة في النظام، ولا يعني اعتمادا بنكيا أو حكوميا تلقائيا.',
    'support.contactAgency': 'تواصل مع وكالتك للحصول على المساعدة.',
  },
};

interface I18nContextValue {
  isRtl: boolean;
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: TranslationKey) => string;
}

const I18nContext = createContext<I18nContextValue | undefined>(undefined);

function normalizeLanguage(value: unknown): AppLanguage {
  return value === 'ar' || value === 'en' || value === 'fr' ? value : 'fr';
}

export function I18nProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<AppLanguage>('fr');

  useEffect(() => {
    let isMounted = true;

    void readStoredJson<AppLanguage>(storageKeys.language, 'fr').then((storedLanguage) => {
      if (isMounted) {
        setLanguageState(normalizeLanguage(storedLanguage));
      }
    });

    return () => {
      isMounted = false;
    };
  }, []);

  useEffect(() => {
    I18nManager.allowRTL(language === 'ar');
  }, [language]);

  const value = useMemo<I18nContextValue>(
    () => ({
      isRtl: language === 'ar',
      language,
      setLanguage: async (nextLanguage) => {
        setLanguageState(nextLanguage);
        await writeStoredJson(storageKeys.language, nextLanguage);
      },
      t: (key) => translations[language][key],
    }),
    [language],
  );

  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const context = useContext(I18nContext);

  if (!context) {
    throw new Error('useI18n must be used inside I18nProvider');
  }

  return context;
}
